general:
  buildTool: "npm"
  chartPath: chart
service:
  buildToolVersion: "N18"
stages:
  Build:
    npmExecuteLint: true
  Additional Unit Tests:
    npmExecuteScripts: true
  Acceptance:
    kubernetesDeploy: false
  Compliance:
    sonarExecuteScan: false
  Release:
    kubernetesDeploy: true
    deploymentName: incidents-mgmt
    kubeConfigFileCredentialsId: kube-config
    namespace: incidents-namespace-cicd
    additionalParameters:
    - --set-file
    - xsuaa.jsonParameters=xs-security.json
steps:
  npmExecuteLint:
    failOnError: true
  npmExecuteScripts:
    runScripts:
    - "test"
  buildExecute:
    npmRunScripts: [ 'cds-build' ]
    npmInstall: false
    cnbBuild: true
    helmExecute: true
  cnbBuild:
    containerRegistryUrl: 'https://index.docker.io'
    dockerConfigJsonCredentialsId: docker-config
    multipleImages:
      - path: gen/srv
        containerImageName: diyadhansap/incident-mgmt-srv
        containerImageAlias: diyadhansap/incident-mgmt-srv
        containerImageTag: latest
      - path: gen/db
        containerImageName: diyadhansap/incident-mgmt-hana-deployer
        containerImageAlias: diyadhansap/incident-mgmt-hana-deployer
        containerImageTag: latest
      - path: app/incidents
        containerImageName: diyadhansap/incident-mgmt-html5-deployer
        containerImageAlias: diyadhansap/incident-mgmt-html5-deployer
        containerImageTag: latest
  helmExecute:
    helmCommand: dependency
    dependency: update